name: iOS One-Time Setup

on: 
  workflow_dispatch:
    inputs:
        environment:
          type: environment
          description: Which environment to deploy to
          default: 'Base-Sandbox-Development'

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ secrets.REPO_NAME }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          #bundler-cache: true

      - name: Build iOS
        shell: bash
        run: |
          bundle install
          bundle exec fastlane ios init_ci
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }} # Raw .p8 value
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}

          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ secrets.REPO_NAME }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}