name: Test Patchkit Tools

on: 
  workflow_dispatch:

jobs:
  testPatchkitTools:
    name: Test Patchkit Tools
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-2019", "macos-latest", "windows-latest"]

    steps:
      - uses: Battle-Nations/Patchkit-Actions@main
